#!/usr/bin/env bash
# detect gnu-make syntax and run gmake, if available
# otherwise, run make

hashq() { hash "$1" 2>/dev/null; }

declare -a arguments=()
makefile=
opt-extract-filename()  {
    local opt="$1" n=1 nn= skip= f= i=
    shift
    for i in "$@"; do
        let nn=n+1 || :
        if [[ -n $skip ]]      ; then unset skip      ; : $i   ; continue ; fi
        if [[ $i == ${opt}  ]] ; then makefile=${!nn} ; skip=1 ; continue ; fi
        if [[ $i =~ ${opt}. ]] ; then makefile=${i:2} ; : $i   ; continue ; fi
        arguments+=("$i"); n=$nn
    done
}

opt-extract-filename -f "$@"

[[ -n $makefile ]] && [[ ! -f $makefile ]] && {
    echo not a file: $makefile >&2;
    exit 1; } 

[[ -z $makefile ]] && makefile=Makefile

match_gnumake() {
    grep $makefile -m1 -E \
        -e '\$\((shell|wildcard)' \
        -e '^(ifeq|ifneq|ifdef|define)'
}

if match_gnumake; then
    if hashq gmake; then
        gmake -f $makefile "${arguments[@]}"
        exit $?
    fi
fi

make -f $makefile "${arguments[@]}"
