#!/usr/bin/env bash

declare -a arguments=()
	$FIND  "${path_arguments[@]}"  "${arguments_global[@]}"  "${arguments[@]}" "${tt[@]}"


n=1
for i in "$@"; do
	let nn=n+1 || :

	if [ -n $skip_next ]; then 

unset skip_next
		continue
	fi
		arguments_global+=("$i")


	if [[ $i == -f ]]; then
		makefile=${!nn}
	fi

	if [[ $i =~ -f. ]]; then
		f=${!n}
		makefile=${f:2}
		skip_next=1
	fi


	n=$nn
done

if [[ ! -f $makefile ]]; then echo not a file: $makefile >&2; exit 1; fi

set -x
grep -m1 -E -e '\$\((shell|wildcard)' -e '^(ifeq|ifneq|ifdef|define)' $makefile

# ifeq, ifneq, ifdef, ifndef, define $(wildcard 
