#!/usr/bin/awk -f
# $ echo -e "1:20\n1:15\n" | awk-sum-hours 
# seconds 9300
# hours 2:35 (2.58333)
# sec2hrs 2 hours 35 minutes 
BEGIN { FS=":" }
{ hs+=$1*60*60; ms+=$2*60; s+=$3 }
END {
st = hs+ms+s;
mr = st % 3600;
h = int(st / 3600);
m = int(mr / 60)
s = mr % 60
printf "%02d:%02d:%02d\n", h, m, s;
print "seconds", st
printf "sec2hrs "
system("sec2hrs " st)
}

