#!/bin/bash

where=${1:-.}

echo btrfs filesystem show
btrfs filesystem show

echo
echo btrfs filesystem usage "$where"
btrfs filesystem usage "$where"

echo
echo btrfs filesystem df  "$where"
btrfs filesystem df  "$where" | tr : , | column  -ts,




