#!/bin/sh
# url=http://team-trafikk.no/team_bussorakel.asp

curl=/usr/bin/curl # -# -d "
opts="-s --connect-timeout 5 --sslv3"
url="https://www.atb.no/xmlhttprequest.php?service=routeplannerOracle.getOracleAnswer&question="

question=`echo $@ |sed "
	s/å/%C3%A5/g
	s/æ/%C3%A6/g
	s/ø/%C3%B8/g
	s/\ /%20/g"`

date +"Tiden er nå: %T (%a, %_d. %b)%n"

$curl $opts "$url$question" | sed '
	/Holdeplassen nærmest.*/ {
		s/\.\ /.\n/
	}
	
	s/går fra/\n\t&/g
	s/kl\./\n    kl./g
	s/og buss/og\nbuss/
	s/og kommer til \(.*\),\(.*\)minutter senere/\n    og kommer til \1,\2 minutter senere/
	s/Tidene angir tidligste.*/\n&\n/

'
