#!/bin/bash


#find ~ -path '*chrome*' -name Cache                           -print -type d 
find ~ \
	'(' \
		-path '*chrome*' \
		-or -path '*chromium*' \
	')' \
	-and \
	'(' \
		-name Cache \
		-or -name IndexedDB \
		-or -name 'Service Worker' \
	')' \
	-print -type d 
                                                                       
#find ~ -path '*chrome*' -name IndexedDB                 -print -type d 
#find ~ -path '*chromium*' -name IndexedDB               -print -type d 
#find ~ -path '*chrome*' -name 'Service Worker'          -print -type d 
#find ~ -path '*chromium*' -name 'Service Worker'        -print -type d 
	#()| xargs -0 -I% du -sm "%"

#{
#
#
#find ~ -name 'Code Cache'         -type d -print0 | xargs -0 -I% sh -c 'du -sm "%/"*'
#find ~ -name 'Application Cache'  -type d -print0 | xargs -0 -I% sh -c 'du -sm "%/"*'
#
#} | sort -k2,2 | awk '{print z+=$1, $0}'
