#!/bin/bash
f=$(mktemp /tmp/check-torrent-XXX)
ctorrent -c "$1" > $f
{
	echo "$1"
	if [[ `grep -c ^Directory $f` == 0 ]];then
		grep -e '^<[0-9]>' -m 1 $f
	fi
	grep -e ^Already -e ^Directory $f | awk '!_[$0]++' 

} | tr \\n ' '
echo
