#!/bin/bash
if [[ $# -eq 0 ]]; then
	find -mindepth 1 -maxdepth 1 -name '*torrent' -print0 | xargs -n1 -0 $0
	exit
fi
f=$(mktemp /tmp/check-torrent-XXX)
ctorrent -c "$1" > $f
{
	echo "$1"
	if [[ `grep -c ^Directory $f` == 0 ]];then
		grep -e '^<[0-9]>' -m 1 $f
	fi
	grep -e ^Already -e ^Directory $f | awk '!_[$0]++' 

} | tr \\n ' '
echo
