#!/bin/bash

mkdir -p ~/.config
tmpf=$(mktemp)

{ # curl
_f_curl=~/.config/curlrc
_f_curl=~/.curlrc
echo silent >> $_f_curl
sort -u $_f_curl > $tmpf; mv $tmpf $_f_curl
#touch $_f_curl
#sed -i $_f_curl -easilent
#echo export CURL_HOME=$_f_curl
}

rm $tmpf
