#!/bin/sh
list=`mktemp`
here=`readlink  -f .`
if [ -d "$1" ]; then here=$1 ;fi

out_temp=$here/php.ctags_temp
out=$here/php.ctags

find $here -type f -name \*.php > $list
#echo $here: `wc -l $list | cut -d ' ' -f1` php files - user: $USER


exuberant-ctags \
	-f $out_temp \
	-V \
	-L $list \
	-h '.php' \
	--exclude=\"\.git\" \
	--PHP-kinds=+cidfv \
	--language-force=PHP \
	--regex-PHP='/(abstract)?\s+class\s+([^ ]+)/\2/c/' \
	--regex-PHP='/(static|abstract|public|protected|private)\s+(final\s+)?function\s+(\&\s+)?([^ (]+)/\4/f/' \
	--regex-PHP='/interface\s+([^ ]+)/\1/i/' \
	--regex-PHP='/\$([a-zA-Z_][a-zA-Z0-9_]*)/\1/v/' \
	> /tmp/php.ctags.log

rm -f $list
mv -f $out_temp $out
