#!/bin/bash

declare -a args=()

if [[ $# -eq 0 ]]; then
	for i in *.torrent; do
		bash $0 "$i"
	done
	exit
fi

for i in "$@"; do
	if [[ -f "$i" ]]; then torr=$i;
	else args[${#args[@]}]=$i; fi
done

if ! [[ -f "$torr" ]]; then
	echo not a file: $torr >&2
	exit 1
fi

torr_dir="$(dirname "$torr")"
torr_fil="$(basename "$torr")"
cd "$torr_dir"
echo ctorrent "'$torr_fil'" "${args[@]}" >&1
exec ctorrent -dd "$torr_fil" "${args[@]}"

