#!/usr/bin/env bash

find . -name '*.torrent' -or -name '*.finished' | sed -E 's/\.(finished|torrent)$//' | awk-count-dupes | grep -v -e ^2 | awk '{
	p = $0
	gsub("1 ", "", p)
	print "ctorrent-pwd \"" p ".torrent\""
}'
