#!/usr/bin/env bash

onlysec=0
if [[ $1 == -s ]]; then onlysec=1; shift; fi

now=$(  date +%F                 2>/dev/null || gdate +%F                )
from=$( date -d "$1" +%s         2>/dev/null || gdate -d "$1" +%s        )
to=$(   date -d "${2:-$now}" +%s 2>/dev/null || gdate -d "${2:-$now}" +%s)


if [[ $from -gt $to ]]; then
	_f=$to
	to=$from
	from=$_f
fi

diff=$(( to - from ))


if [[ $onlysec == 1 ]]; then
	echo $diff
else
	echo $diff seconds
	echo $(( diff / 3600 )) hours $(( diff % 3600 / 60 )) mins
	echo $(( diff / 3600 / 24 )) days

	if which sec2hrs 1>/dev/null 2>&1; then
		sec2hrs ${diff/-/}
	fi

fi
