#!/bin/bash

now="$(date)"

if [[ $# -gt 0 ]]; then
	now="$*"
fi


#North_Dakota/Beulah
#North_Dakota/Center
#North_Dakota/New_Salem
#
#Beulah
#Center
#New_Salem

# ETD
# ESD
# PDT
# PST

# export LC_TIME=en_GB

(
echo Here^ `date -d "$now"`
echo - ^ -
for i in `echo "

America/Los_Angeles

UTC+6
EST
UTC+5

UTC+4
America/New_York


UTC+2
UTC+1
UTC+0
UTC
UTC-0

UTC-1
Europe/London
Europe/Oslo
Europe/Dublin
UTC-1
Europe/Berlin
UTC-2
UTC-3
Europe/Moscow

UTC-4
UTC-5
UTC-6
UTC-7
UTC-8
UTC-9
Japan

"`; do
	echo $i^ `TZ=$i date -d "$now"`
done)| column -ts^
#| sort -k 2b -t^ 

# PDT - Pacific Daylight Time
# PST - Pacific Standard Time
# America/Salem


# EST – Eastern Standard Time
# EDT - Eastern Daylight Time
# America/NewYork
# America/Richmond
