#!/bin/bash

## --rfc-3339=seconds

#now="$(date)"
now="$(date "$@" )"

#if [[ $# -gt 0 ]]; then now="$*" fi


#North_Dakota/Beulah
#North_Dakota/Center
#North_Dakota/New_Salem
#
#Beulah
#Center
#New_Salem

# ETD
# ESD
# PDT
# PST

# export LC_TIME=en_GB

(
#echo Here^ `date -d "$now"`
echo Here^ `date "$@"`
echo - ^ -
for i in `echo "

America/Los_Angeles

UTC+6
EST
UTC+5

UTC+4
America/New_York


UTC+2
UTC+1
UTC+0
UTC
UTC-0

UTC-1
Europe/London
Europe/Oslo
Europe/Dublin
UTC-1
Europe/Berlin
UTC-2
UTC-3
Europe/Moscow

UTC-4
Asia/Dubai
Asia/Yerevan
Asia/Kabul
UTC-5


Asia/Singapore
Asia/Manila
Asia/Tbilisi


UTC-6
UTC-7
Asia/Irkutsk
Asia/Krasnoyarsk

UTC-8
Asia/Macau
Asia/Taipei
Asia/Hong_Kong

Indian/Reunion
Indian/Mayotte
Indian/Mahe
Indian/Kerguelen
Indian/Comoro
Indian/Cocos
Indian/Christmas
Indian/Antananarivo
Indian/Maldives
Indian/Chagos
Indian/Mauritius

UTC-9
Asia/Yakutsk
Asia/Chita
Japan
Asia/Vladivostok

"`; do
	#echo $i^ `TZ=$i date -d "$now"`
	echo $i^ `TZ=$i date "$@"`
done)| column -ts^
#| sort -k 2b -t^ 

# PDT - Pacific Daylight Time
# PST - Pacific Standard Time
# America/Salem


# EST – Eastern Standard Time
# EDT - Eastern Daylight Time
# America/NewYork
# America/Richmond
