#!/usr/bin/env bash
a=$1
if [[ ${#1} -eq 4 ]]; then
	set -- $1-01-01
fi
past_ymd=${1:-1987-12-28}
past_y=${past_ymd:0:4}
past_y_next=$(( past_y +1 ))

ymd=`ymd`
y=${ymd:0:4}
y_prev=$((y-1))

{

if [[ $past_y < $y ]]; then
days $past_y | sed -n '/'$past_ymd'/,$p' ;
fi

if [[ $y_prev > $past_y_next  ]]; then

life=`seq $past_y_next $y_prev`
for i in $life; do days $i;done; fi

days $y | sed /$ymd/q ;} | cat -n
