#!/bin/bash


if [[ $# -eq 2 ]]; then
	yFrom=$1
	yTo=$1
	if [[ ${#1} -eq 4 ]]; then yFrom=$1-01-01; fi
	if [[ ${#2} -eq 4 ]]; then yTo=$2-01-01; fi
	d=$( date +%s -d "$yFrom")
	dec=$( date +%s -d "$yTo")
else

	jan01 () { date +%s -d `date +${1:-%Y}-01-01`; }
	dec () { j=`jan01 $1`; echo $((j + 365*24*3600)); }

	d=`jan01 ${1:-%Y}`;
	dec=`dec ${1:-%Y}`;
fi

cash=~/.cache/days.$dec
if [[ -f $cash ]]; then save() { : ;}; cat $cash; exit 0;
else save() { tee $cash; }; fi


while [ $d -lt $dec ];do
	date '+%j %Y-%m-%d %B %V %A ' -d@$d;
	let d=$d+86400;
done | save

