#!/bin/bash

   WORD=$1
   DICT=/usr/bin/dict
COLORIT=/usr/bin/colorit
  PAGER=${PAGER:-/usr/bin/less}
   HIST=$HOME/.dictionary/history

if [ ! -d `dirname $HIST` ]; then
	mkdir `dirname $HIST`
fi

if [ ! -x  $COLORIT ]; then
	COLORIT=/bin/cat
fi

if [ -x $DICT ]; then
	found=`$DICT $WORD 2>/dev/null`
	if [ $? -eq 0 ]; then
		echo "$WORD" >> $HIST
	fi
	lines=`echo -e "$found" | wc -l`
	term=`tput lines`
	if [[ $term -gt 0 && $term -ge $lines ]]; then
		PAGER=/bin/cat
	fi
else
	echo Install dict from http://sf.net/projects/dict
fi

echo -e "$found" | grep -ve From.WordNet | colorit | $PAGER
#$DICT -f "$WORD" | colorit | $PAGER
