#!/bin/dash
RC=$HOME/.eclim/rc-spotn

if [ "$1" = "stop" ];
then
	eclim -f $RC -command shutdown
	exit
elif [ "$1" = "restart" ];
then
	$0 stop 
	exec $0
fi
screen -dmS eclimd eclimd -f ~/.eclim/rc-spotn
while `eclim -f $RC -command ping 2>&1 | grep -q refused `;
do 
	sleep 1; 
	echo -n .;
done

echo
eclim -f $RC -command ping 2>&1 | 
sed 's/[{}"]//g; s/,/\n/; s/:/: /g; s/eclim/  eclim/;'
