#!/usr/bin/env bash
file_line=$(
tac /var/log/php_error.log | grep -m1 Fatal | grep -E -e '/[[:graph:]]+:[0-9]+$' -o | tr : ' ' 
)

echo -e "$file_line" | awk '

	{ print "gvim " $1 " +" $2 }
	{ print "phpstorm --line " $2 " " $1 }
'
