#!/bin/sh

HOME=/home/jaroslav
WALLS=$HOME/images/wallpapers/deviant/grafitti
WALLS1=$HOME/images/wallpapers/s.t.a.l.k.e.r-deviant  
WALLS2=$HOME/images/wallpapers/deviant/2013-12

function find_bg {
	find \
		$WALLS1 \
		$WALLS2 \
		-type f | sort -R | tail -n 1
}

function fbset_next() {
	local BG=`find_bg`
	DISPLAY=${1:-:0.0} fbsetbg -a $BG
	echo $BG
}

#/home/jaroslav/images/wallpapers/deviant/2013-12/The_Bridge_by_Gate_To_Nowhere.jpg
#/home/jaroslav/images/wallpapers/deviant/2013-12/marchin_on_wallpaper_by_apofiss-d310cb9.jpg
alias next_wall=fbset_next

echo $0

[ `basename -- "$0"` = "fbset_next" ] && fbset_next $1
