#!/bin/bash
f="$1"

if echo "$1" |grep -q 'https*://.*'; then
	true
else
	wcp="`which cygpath 2>/dev/null`"
	if [ -x "$wcp" ] ; then
		NICE=""
		f="$(cygpath -w "$1" )" ; 
	fi
fi


if [ "" == "$f" ]; then
	firefox &
else
	firefox "$f" &
fi

sudo renice -n -5 `pidof firefox`
