#!/usr/bin/env bash

search_dir=.
format='-printf "%P\n"'
format0='-printf "%P\0"'
for i in "$@"; do
	if [[ $i == -0 ]]; then format=$format0; fi
	if [[ -d $i ]]; then search_dir=$i; fi
done

if [[ $search_dir != . ]]; then

	format=${format/\%P/$search_dir/%P}
	format=${format/\/\///}
	#echo D::$search_dir::
	#echo F::$format::
fi

declare -a exttype_video=( mp4 avi mov wmv mkv flv webm mpeg mpg )
declare -a exttype_audio=( mp3 wav aac ogg flac wma )
declare -a exttype_image=( jpg jpeg png gif bmp tiff tif webp )

types() { echo $(
declare -p | sed -n '/declare -a exttype/{ s/=.*// ; s/.*exttype_// ; p}'
); };

search_files() {
    local type=$1
    local extensions=("${!2}")

    eval find "'$search_dir'" -type f \\\( $(printf -- "-iname '*.%s' -o " "${extensions[@]}" ) -false \\\) "$format"
}

case "$1" in
    video) search_files $1 exttype_video[@] "${2:-}" ;;
    audio) search_files $1 exttype_audio[@] "${2:-}" ;;
    image) search_files $1 exttype_image[@] "${2:-}" ;;

    vid) search_files $1 exttype_video[@] "${2:-}" ;;
    aud) search_files $1 exttype_audio[@] "${2:-}" ;;
    img) search_files $1 exttype_image[@] "${2:-}" ;;
    pic) search_files $1 exttype_image[@] "${2:-}" ;;


    #
	*) echo "Usage: $(basename "$0") <$(types | tr ' ' '|' )> [where]" ;;
esac

