#!/bin/sh

# gentoo
#RTFILE=/opt/sun-jdk-1.6.0.29/jre/lib/rt.jar
#RTFILE=/opt/sun-jdk-*/jre/lib/rt.jar

# debian
RTFILE=/usr/lib/jvm/java-6-sun-1.6.0.21/jre/lib/rt.jar

# gentoo
RTFILE=/opt/oracle-jdk-*/jre/lib/rt.jar



JAR=/usr/bin/jar

if [ "$#" -lt 1 ];then 
	echo "you need to give me a class name to look for"
	exit 1
fi

if [ -x $JAR ];then 
	if [ -f $RTFILE ]; then 
		for i in `\
		jar tf $RTFILE \
		| tr '/$' '..' \
		| sed 's/\.class$//' \
		| sort | grep "$1$" `

		do 
		  echo -e "import $i;" 
		done
	else 
		echo "install java.."
		echo "i cant find $RTFILE"
	fi
else 

	echo "install java.. (no jar in path)"

fi 

