#!/bin/bash
#echo -- $@
#echo -- $1
#echo "$1"
#echo "???"
D=0

for i; do 
	#echo $i
	if [ "$i" = "@" ] ; then D=1; break; fi

	if [ -d "$i" ];   then
		where=$i; continue; fi

	args="$args $(
	# echo bug: echo -n '-n' -n
	echo @%$i | sed -E '
	s/^@%//
	s/^-t?f$/-type f/
	s/^-t?d$/-type d/
	s/^-n$/-name/
	s/^-i$/-iname/
	')"
done

if [[ $1 = $args ]]; then
	eval /usr/bin/find $where -name "*$1*"
	exit
fi

if [ $D -gt 0 ];then echo /usr/bin/find $where $args; fi
eval /usr/bin/find $where $args


