#!/usr/bin/env bash

# simplified interface to find
# examples:
#
#    # read-ahead (cat everything into fs-cache)
#    finn images.from.archives/ -f -0 | xargs -0 -n3 -P40 cat | pv >/dev/null

Quiet=0
Debug=0

FIND=/usr/bin/find
if [ -f $HOME/opt/findutils/libexec/gnubin/find ]; then
	FIND=$HOME/opt/findutils/libexec/gnubin/find
fi

#export FIND

where=.

isElementIn () {
	local e match="$1"
	shift
	for e; do [[ "$e" == "$match" ]] && return 0; done
	return 1
}

declare -A short=(
	[-d]=-type\ d
	[-f]=-type\ f
	[-td]=-type\ d
	[-tf]=-type\ f
	[-tl]=-type\ l
	[-n]=-name  # Bug if one of these is passed, use it for all "terms"
	[-i]=-iname # Bug
	[-max]=-maxdepth
	[-min]=-mindepth
	[-S]=-size
	[-0]=-print0
)

declare -a before_other=(
	-maxdepth
	-mindepth
)

declare -a arguments_global=()
declare -a arguments=()
declare -a terms=()
declare -a path_arguments=()

and_next=0
and_next_short=0
for i in "$@"; do

	if [ "$i" = "@@" ] ; then Quiet=1; continue; fi
	if [ "$i" = "@" ] ; then Debug=1; continue; fi

	if [ ${short[$i]+true} ]; then
		for si in ${short[$i]}; do

			if isElementIn "$si" "${before_other[@]}"; then
				arguments_global+=("$si")
				and_next=1 # e.g. -maxdepth 55 . next is 55
				# make a map for these to ?
			else
				arguments+=($si)
			fi

		done
		continue
	fi


	if [ $and_next -eq 1 ]; then
		arguments_global+=("$i")
		and_next=0
		continue
	fi


	if [ -d "$i" ];then
		path_arguments+=( "$i" )
		continue
	fi

	if [[ $i =~ ^[+-] ]]; then
		arguments+=("$i")
	else
		terms+=("$i")
	fi

done

if [[ ${#path_arguments[@]} -eq 0 ]]; then
    path_arguments+=( $where )
fi

if [ $Debug -gt 0 ];then
	(
	echo
	echo Meta: Debug:$Debug Quiet:$Quiet
	echo Path: "${path_arguments[@]}"
	echo GLOB: "${arguments_global[@]}"
	echo ARG..: "${arguments[@]}"
	let ai=1; for a in "${arguments[@]}"; do
		echo "   .$((ai++)):" $a
	done
	echo F: find  "${path_arguments[@]}"  "${arguments_global[@]}"  "${arguments[@]}"
	echo
	) >&2
fi
		
declare -a tt=()
for i in ${terms[@]}; do
	tt+=(-iname)
	tt+=(\*"$i"\*)
done

if [ $Quiet -gt 0 ]; then
	exec 2>&-
fi
set -x
$FIND  \
	"${path_arguments[@]}" \
	"${arguments_global[@]}" \
	"${arguments[@]}" \
	"${tt[@]}" \
| sed -e 's,^\./,,'
