#!/bin/bash

chmod go-rwX ~
chmod go-rwX ~/.ssh;
chmod go-rwX ~/.ssh/authorized_keys

if [[ $UID != 0 ]]; then
	exit
fi

chmod go-rwX /home/*
chmod go-rwX /home/*/.ssh;
chmod go-rwX /home/*/.ssh/authorized_keys

usernames() { (
	find /home -maxdepth 1 -mindepth 1 | sed s:/home/::;
	whoami
) | sort -u; }

fix_for_user() { 
	local me=$1
	local home=$(eval echo ~$me)
	if id $u &>/dev/null; then
		printf "[%-10s :%s:]\n" $me $home
		chmod go-w            $home
		chown $me:$me         $home/{.,.ssh/,.ssh/authorized_keys}
		chmod u+rwX,go-rwX,-t $home/{.ssh/,.ssh/authorized_keys}
	fi
}

for u in `usernames`; do
	fix_for_user "$u"
done
