#!/bin/bash
function dict {

	if [ -f /usr/share/aspell/nb.cwl.gz ]; then
		zcat \
			/usr/share/aspell/nn.cwl.gz  \
			/usr/share/aspell/nb.cwl.gz | strings;
	elif [ -f "/usr/lib*/aspell*/no.rws" ]; then
		strings /usr/share/lib*/aspell*/no.rws
	fi
}

words=$( dict |
sort -u | sort -R  |
tr -d $'\t' | tail -n 3 |
tr \\n ' ' |
tr 'A-Z' 'a-z' ;
)

special() {
	tr -dc '[:graph:]'  < /dev/urandom | 
	tr -d '[:alpha:]' |
	dd bs=1 count=3 2>/dev/null
}

for i in $words; do
 echo -n "$i "; special; echo -n " "
done
echo

