#!/bin/sh
words=$(
strings  /usr/lib64/aspell-0.60/no.rws |
sort -u | sort -R  |
tr -d $'\t' | tail -n 3 |
tr \\n ' ' |
tr 'A-Z' 'a-z' ;
)

special() {
	tr -dc '[:graph:]'  < /dev/urandom | 
	tr -d '[:alpha:]' |
	dd bs=1 count=3 2>/dev/null
}

for i in $words; do
 echo -n "$i "; special; echo -n " "
done
echo

