#!/bin/bash
where="${1:-.}"
function git-dirs() { find "$where" -name .git; }
for i in `git-dirs`; do
	work_dir="$(dirname $(realpath "$i"))"
	(
		if cd "$work_dir" 2>/dev/null; then
			pwd
			git gc 2>/dev/null
			if [[ $? -eq 128 ]]; then
				echo added "'safe'" $work_dir
				git config --global --add safe.directory "$work_dir"
				git gc
				echo
			fi
		fi
	)
done
