#!/usr/bin/env bash -l

gb=${1:-16000}
curr=${2:-235}

if [[ `imath "$gb < $curr"` -eq 1 ]]; then
	echo oops: $gb gb is less than currency $curr
fi

curr_per_tera=$(math $curr / [ $gb / 1000 ])

printf "%1.1f = %.2f [€$] / %.1f tb\n" $curr_per_tera $curr $(math $gb/1000) | sed  's/\.0\+\>//g'
