#!/bin/dash
## sudo hdparm -I /dev/sd? 2>&1 | sed -n -E '
## # [ 1 ]
## /(^\/)|(Model|Serial N|Firmware|1000\*1000)/!d
## /(^\/)|(Model|Serial N|Firmware|1000\*1000)/{
## /[[:space:]]*(Model|Serial) Number:[[:space:]]*/ { s/// }
## /[[:space:]]Firmware Revision:[[:space:]]*/ { s/// }
## /.*1000\*1000.*\((.*)\)$/ { s//\1/ }
## p } '| tr \\n : | sed -E ' 
## s| +||g
## s|/[^:]*:|\n&|g
## s|::|:|g
## ' | column -s: -t


# notes. 
# 
# flashvoyager configured as a non-removable drive would generate garbage and
# disrupt the output. Sometimes that would result in dublicate rows for one 
# hard drive. the awk version prints each serial number only once. 
# THE DEVICE COULD STILL BE WRONG.
# 


sudo hdparm -I /dev/sd? 2>/dev/null | awk '

BEGIN { 
	FS=":"
}

/\/dev\/sd.:/ { 
	gsub(/\ +/, "", $1);
		
	DEV=$1

}

/Model Number:/ {
	gsub(/\ +$/, "", $2);
	gsub(/^\ +/, "", $2);
	MODEL=$2
}

/Serial Number:/ {

	gsub(/\ +$/, "", $2);
	gsub(/^\ +/, "", $2);

	SERIAL=$2
}
/Firmware Revision:/ {

	gsub(/\ +$/, "", $2);
	gsub(/^\ +/, "", $2);

	FIRMWARE=$2
}

/1000\*1000:/ {

	gsub(/.*\(/, "", $0);
	gsub(/\)/, "", $0);
	CAPACITY=$0	
		
}

/Transport:/ {
	
}


/^Commands/ {


	if ( ! one_line_per_dev[SERIAL]++) {
		printf "%s:%s:%s:%s:%s\n", DEV, MODEL, SERIAL, FIRMWARE, CAPACITY
	}

	CAPACITY=""	
	FIRMWARE=""
	DEV=""
	MODEL=""
	SERIAL=""

}

{}


' | column -ts:
