#!/bin/sh



if hash ip &>/dev/null; then
	ip -json  addr  | jq '[.[]|{
	ifname,
	inet4: (.addr_info[] | select(.family== "inet").local),
	inet6: (.addr_info[] | select(.family== "inet6").local),
	mac:.address,
	link_type
	# , broadcast
	}] | [.[]| with_entries(.key|=ascii_downcase)]|(.[0] |keys_unsorted | @tsv) , (.[]|.|map(.) |@tsv)' -r \
	  | column  -t -s '	'
else

	ifconfig | awk '
BEGIN { i=0 } 

/^[a-z0-9]+:/ {
	n=i;
	name=$1; sub(":", "", name) ; names[i]=name;
	i++ }

$1 == "inet" { inets[name]=$2 }
$1 == "inet6" { inets6[name]=$2 }


END {
	for (i in names) {
		name=names[i];
		i4 = inets[name]
		i6 = inets6[name]
		if (i4 == "") { i4="-" }
		if (i6 == "") { i6="-" }
		printf "%-7s %-15s %s\n", name, i4, i6
		}
	}
'

fi
