#!/bin/sh

if [ ! -f "$1" ];then 
	echo "public class `basename $1 .java` {" > $1
	echo "public static void main(String[] argv) {" >> $1
	echo "}}" >> $1
fi

[ $2 ] && [  "$3" == "" ] && vim $1
javac $1 && java `basename $1 .java` $@


