#!/usr/bin/env bash
#realpath "$1" --relative-to=$where ||

frm() { { test -e "$1" && echo $1 || echo "## $1";  } 2>/dev/null; }
to() { { readlink "$where/$1"     || echo "[$1>>]"; } 2>/dev/null; }

export -f frm to
export where=${1:-.}

find $where -maxdepth 1 -mindepth 1 -type l  \
	| sed s:^\./:: \
	| xargs -P0 -I% bash -c 'echo $(frm %)^$(to %)' \
	| column -ts^

