#!/usr/bin/env bash
#
# lssort lists files in a folder in a structured way, usually
# taking less space for the output than normal ls would.
#
# - list dirs starting with _ first
#   then dirs
#   then files
#   then symlinks and other stuff
#
# - lists files after folders like windoze explorer
#   now also possible with: ls --group-directories-first
#
# bugs:
#    - <> in filename
#    - device files are missing
#
# files named e.g -l (valid parameters)
#

function trim {
    local var="$*"
	#$ var="  hello space    "
	#$ echo "<<${var%%[![:space:]]*}>>"
	#$ <<  >>

    var="${var#"${var%%[![:space:]]*}"}" # rm leading whitespace characters
    var="${var%"${var##*[![:space:]]}"}" # rm trailing whitespace characters

    var="${var#"${var%%[![\\0]*}"}" # rm leading nulls characters
    var="${var%"${var##*[![\\0]}"}" # rm trailing nulls characters
    echo -n "$var"
}

function arrayContains {
	# remove the shortest needle from array and compare lengths
	# needs more testing...
	declare -a array
	declare -a arrayLess
	declare needle
	array=( "${!1}" ); shift 		# expand the passed array name
	needle="$*"						# try to match the rest as a string
	arrayLess=( `trim "${array[@]#${needle}}"` )	# remove value $needle
	if [ ${#array[@]} -eq 0 ];then 					return 1 ;fi
	if [ ${#array[@]} -eq ${#arrayLess[@]} ];then	return 1 ;fi
	if [ ${#array[@]} -lt ${#arrayLess[@]} ];then	return 1 ;fi
	return 0
}

# d dir f file p named pipe (FIFO) l sylink s socket D door (Solaris)
# c character (unbuffered) special b block (buffered) special

# mindepth 1 excludes the . directory
# -depth causes depth-first traversal
function finddirs_ { $FIND "$@" -mindepth 1 -maxdepth 1 -depth -type d      -name '_*' -printf '%f\0'; }
function finddirs  { $FIND "$@" -mindepth 1 -maxdepth 1 -depth -type d -not -name '_*' -printf '%f\0'; }
function findfiles { $FIND "$@" -maxdepth 1             -depth -type f                 -printf '%f\0'; }

function findspecials {
	$FIND "$@" \
		-maxdepth 1 -depth \( -type l   -o -type p  -o -type s -o -type b -o -type c \) \
		-printf "%f\0"
}

function filter_out_hidden {
	local notdots='^\..*'
	# show hidden files after all if called like `lssort -[aA]`
	if [[ $LSSWITCHES =~ -[aA] ]]; then
		notdots='/x/123/tt/7/1/zzx/ooo/'
	fi
	$GREP -zv -e "$notdots" \
		-e '^System Volume Information$' \
		-e '\$RECYCLE\.BIN' \
		-e '/c/Users/jazzo/bin/lssort' \
		-e ^NTUSER.DAT
}

##
## vars and such
##
# shellcheck disable=SC2034
validswitches=(-X -l -r -t -C -F -1 -a -A -d -s -v)
PATHS=()
FPATHS=""
LSSWITCHES="-v"


LS=ls
GREP=grep
FIND=find

[[ -f /usr/local/bin/find ]]  && GREP=/usr/local/bin/find
[[ -f /usr/local/bin/grep ]]  && GREP=/usr/local/bin/grep
[[ -f /usr/local/bin/ls   ]]  &&   LS=/usr/local/bin/ls

GNUBIN=/Users/`whoami`/opt/grep/libexec/gnubin # os x brew

[[ -f $GNUBIN/ls   ]] && LS=$GNUBIN/ls
[[ -f $GNUBIN/grep ]] && GREP=$GNUBIN/grep
[[ -f $GNUBIN/find ]] && FIND=$GNUBIN/find

function hasbin() { hash "$1" &>/dev/null; }

hasbin gls   && LS=gls
hasbin ggrep && GREP=ggrep
hasbin gfind && FIND=gfind

LS="$LS --color=auto"

ARG=$1
ARGC=0
while [ "$ARG" != "" ];
do
	if arrayContains validswitches[@] $ARG;
	then
		LSSWITCHES="$LSSWITCHES $ARG"
		unset ARG
	fi

	if [ -d "$ARG" ];then
		#PATHS="${PATHS} $ARG"
		#shellcheck disable=SC2004
		PATHS[$ARGC]=$ARG
		let ARGC=ARGC+1
	else
		FPATHS="$FPATHS\0$ARG"
	fi
	shift
	ARG=$1
done

#PATHS=`trim $PATHS`
FPATHS=`trim "$FPATHS"`

if [ ${#FPATHS} -eq 0 ]; then
	if [ ${#PATHS[@]} -eq 0 ]; then
		PATHS=(".")
	fi
fi
for arg in "${PATHS[@]}";
do
	if [[ ${#arg} -eq 1 && "$arg" == "/" ]];then
		p=/
	else
		#p=${arg%%/}
		p=$arg
	fi

	# shellcheck disable=SC2119
	( cd "$p"

		#export LC_COLLATE="C"

		if [[ "$p" != "." && "$p" != "./" ]];then echo "$p": ;fi

		[[ -n $DEBUG ]] && v=-t
		#[[ -n $DEBUG ]] && set -x

		findspecials | filter_out_hidden | xargs $v -r0 $LS $LSSWITCHES -d --
		finddirs_    | filter_out_hidden | xargs $v -r0 $LS $LSSWITCHES -d --
		finddirs     | filter_out_hidden | xargs $v -r0 $LS $LSSWITCHES -d --
		findfiles    | filter_out_hidden | xargs $v -r0 $LS $LSSWITCHES    --
		[ ${#PATHS[@]} -gt 1 ] && echo
	)
done

if [ -n "$FPATHS" ]; then

	echo -ne "$FPATHS\0" | xargs $v -0 -r $LS $LSSWITCHES --
fi

