#!/bin/bash
# sort by header-name length
# output headers exceeding terminal width
# output short headers
# output common headers

width=`tput cols`

pre() { cat; }
if [[ $# -gt 0  ]];then
echo
	pre() { cat "$@"; }
fi

pre "$@" | sed '/^$/q' |
	reformime -u |
	sed -e 's/\ \+/ /g' |
	awk -v cc=$width -v only=$only_headers '
		function sort_headers(ia, va, ib, vb) {
			a_colon = index(va, ":");
			b_colon = index(vb, ":");
			return length(substr(vb, 0, b_colon)) - length(substr(va, 0, a_colon))
		}
		{ keep="" }
		$0 ~ /^Cc:/ { keep=$0; }
		$0 ~ /^To:/ { keep=$0; }
		$0 ~ /^From:/ { keep=$0; }
		$0 ~ /^Date:/ { keep=$0; }
		$0 ~ /^Subject:/ { keep=$0; }
		$0 ~ /^List-ID:/ { keep=$0; }
		$0 ~ /^Reply-To:/ { keep=$0; }
		$0 ~ /^Return-Path:/ { keep=$0; }
		$0 ~ /^Delivered-To:/ { keep=$0; }
		$0 ~ /^Mailing-List:/ { keep=$0; }
		$0 ~ /^X-GMAIL-LABELS:/ { keep=$0; }
		$0 ~ /^X-GMAIL-MSGID:/ { keep=$0; }
		$0 ~ /^X-BeenThere:/ { keep=$0; }
		$0 ~ /^X-getmail-retrieved-from-mailbox:/ { keep=$0; }
		{
			if (length(keep)) {
				last[k++]=keep
			} else {
				if (length($0)>cc) {
					long[l++] = substr($0, 1, cc-3) " x" 
				} else {
					short[s++] = $0
				}
			}
		} END {
			PROCINFO["sorted_in"] = "sort_headers"

			if (only == "") {
				for (i in long) { print long[i] }; print ""
				for (i in short) { print short[i] }; print ""
				for (i in last) { print last[i] }
			}

			if (only == "last") {
				for (i in last) { print last[i] }
			}
	}' 
