#!/bin/bash
# 
# List all sections of a manpage.

# Uses lesspipe (gentoo portage mirror)
# /usr/portage/sys-apps/less/files/lesspipe.sh
# v01: MANPAGER=cat man $@ | grep -E '^^[[1m[A-Z]{3,}'

MAN=$(find ${MANPATH//:/ } | grep "/$1\.")


#eval $(sed -n -e /^guesscompress/,/^}/p /usr/bin/lesspipe)
guesscompress() {
	case "$1" in
		*.gz|*.z)   echo "gunzip -c" ;;
		*.bz2|*.bz) echo "bunzip2 -c" ;;
		*.lz)       echo "lzip -dc" ;;
		*.lzma)     echo "unlzma -c" ;;
		*.lzo)      echo "lzop -dc" ;;
		*.xz)       echo "xzdec" ;;
		*)          echo "cat" ;;
	esac
}

if [ -f /usr/bin/lesspipe.sh ]; then source /usr/bin/lesspipe.sh; fi
if [ -f /usr/bin/lesspipe ]; then source /usr/bin/lesspipe; fi

READ=$(guesscompress .${MAN##*.})


#$READ $MAN | grep -E -e '^\.SH' | sed 's/^.SH //'
$READ $MAN | sed '/^\.SH/!d; /^\.SH/{ s/^....// }'
