#!/bin/bash
# List all sections of a manpage.
#
# Uses guesscompress from lesspipe (gentoo)
# /usr/portage/sys-apps/less/files/lesspipe.sh
#
# v01: MANPAGER=cat man $@ | grep -E '^^[[1m[A-Z]{3,}'
# v02: use gentoo lesspipe
# v03: extract guesscompress
# v04: 2019-12; fix manpath on ubuntu, or search folders

guesscompress() {
	case "$1" in
		*.gz|*.z)   echo "gunzip -c" ;;
		*.bz2|*.bz) echo "bunzip2 -c" ;;
		*.lz)       echo "lzip -dc" ;;
		*.lzma)     echo "unlzma -c" ;;
		*.lzo)      echo "lzop -dc" ;;
		*.lz4)      echo "lz4 -dc" ;;
		*.xz)       echo "xzdec" ;;
		*)          echo "cat" ;;
	esac
}
mans=
if type manpath 2>/dev/null; then
	mans=$(manpath)
elif [[ -n $MANPATH ]]; then
	mans=$MANPATH
else
	mans=$(find /usr/share /usr/local -maxdepth 2 -name man -type d | tr $'\n' :)
fi
if [[ -z $mans ]];then
	echo unable to detect manual paths
	exit 1
fi
MAN=$(find ${mans//:/ } | grep "/$1\.")
READ=$(guesscompress .${MAN##*.})
$READ $MAN | sed -E '
	/^.(SH|SS)/!d; 
	s/^.SH //;
	s/^.SS /    /;
	s/"//g;
'
