#!/bin/bash
# List all sections of a manpage.
#
# Uses guesscompress from lesspipe (gentoo)
# /usr/portage/sys-apps/less/files/lesspipe.sh
#
# v01: MANPAGER=cat man $@ | grep -E '^^[[1m[A-Z]{3,}'
# v02: gentoo lesspipe
# v03: extract guesscompress

guesscompress() {
	case "$1" in
		*.gz|*.z)   echo "gunzip -c" ;;
		*.bz2|*.bz) echo "bunzip2 -c" ;;
		*.lz)       echo "lzip -dc" ;;
		*.lzma)     echo "unlzma -c" ;;
		*.lzo)      echo "lzop -dc" ;;
		*.lz4)      echo "lz4 -dc" ;;
		*.xz)       echo "xzdec" ;;
		*)          echo "cat" ;;
	esac
}
MAN=$(find ${MANPATH//:/ } | grep "/$1\.")
READ=$(guesscompress .${MAN##*.})
$READ $MAN | sed -E '
	/^.(SH|SS)/!d; 
	s/^.SH //;
	s/^.SS /    /;
	s/"//g;
'
