mpc-remove 'lords of acid'
mpc-remove 'gusgus'
mpc-remove 'johan sebastian bach'
mpc-remove 'The Climax Blues Band'
mpc-remove 'mozart'
mpc-remove 'burning spear'
mpc-remove 'bob marley' 
mpc-remove 'king tubby'
mpc-remove 'burning_spear'
mpc-remove 'высоцкий'
mpc-remove 'vysotsky'
mpc-remove 'Розенбаум'
mpc-remove 'Машина времени'
mpc-remove 'Андрей Макаревич'
mpc-remove 'tom waits'
mpc-remove 'nick cave' 
mpc-remove 'beatles'

mpc-remove 'devendra banhart'
mpc-remove 'slayer' 
mpc-remove 'cab caloway' 
mpc-remove 'bob dylan'
mpc-remove 'dr. bekken'
mpc-remove 'john zorn'
mpc-remove 'matisyahu'
mpc-remove 'cypress hill'
mpc-remove 'thievery corporation'
mpc-remove 'public enemy'
mpc-remove 'andre 3000'
mpc-remove 'sean paul'
mpc-remove 'benny goodman'
mpc-remove canibus
mpc-remove 'dj fabio'
mpc-remove 'Creedence Clearwater Revival' 
mpc-remove 'Lupe Fiasco'
mpc-remove 'gg allin' 
mpc-remove 'jokke and val'
mpc-remove 'Тимур Шаов'
mpc-remove 2pac
mpc-remove 'britney spears'
mpc-remove 'Violent Onsen Geisha'
mpc-remove 'warren g'
mpc-remove fdt-troenderske_signaler
mpc-remove 08-rap 
mpc-remove 'Project pitchfork' 
mpc-remove 'everlast' 
mpc-remove 'the velvet underground' 
mpc-remove 'the clash' 
mpc-remove pogues

mpc-remove 'Duke Ellington & His Orchestra' 
mpc-remove 'Michael Jackson' 

