#!/bin/dash
#NAILGUN_SERVER=127.0.0.1
#NAILGUN_PORT=2113
# -or-
# java -server com.martiansoftware.nailgun.NGServer hostname:port

NG=/usr/bin/ng
NGCP=$HOME/.nailgun/classpath
MYCP=$(
	find $NGCP -perm 755 -name \*cp  | xargs cat | tr \\n :  | sed s/:$//
)


$NG NoClazz555 2>&1 | grep -q 'Connection refused' &&
screen -dmS nailgun$NAILGUN_PORT \
java -cp $MYCP com.martiansoftware.nailgun.NGServer &&
echo server up

$NG ng-alias jsh bsh.Console
$NG ng-alias shell bsh.Console

$NG $@
