#!/bin/sh
export CHARSET=
export LC_ADDRESS=
export LC_COLLATE=
export LC_CTYPE=
export LC_IDENTIFICATION=
export LC_MEASUREMENT=
export LC_MESSAGES=
export LC_MONETARY=
export LC_NAME=
export LC_NUMERIC=
export LC_PAPER=
export LC_TELEPHONE=
export LC_TIME=
export LESSCHARSET=
exec"$@"

