#!/bin/sh
if [[ -n $2 ]]; then
openssl s_client -showcerts -connect ${1:-silicamagazine.com}:443 < /dev/null  |& cat
else 
openssl s_client -showcerts -connect ${1:-silicamagazine.com}:443 < /dev/null  |& grep CN.=.* -o
fi
