#!/bin/bash -x
from=${1:-/G/distfiles}
to=${2:-/R/os-files/mirror/gentoo/distfiles}

rr() {
if [[ -d "$1" ]]; then d=/; fi
rsync -a -h -i --info=stats1 "$1$d" "$to/$1$d"; };
export -f rr
export to

cd "$from" || { echo "can not cd to '$from'"; exit 2; }

a=`date +%s`

if timeout 20s rsync -a $from/ $to/; then
	:
else
	find -mindepth 1 -type d -print0 | parallel -0 -j32  rr ::::
	find             -type f -print0 | parallel -0 -j32  rr ::::
fi

echo "done in sec: $(( `date +%s` - a ))" >&2
