#!/bin/bash
set -e

# Steps to set up a new secrets partition
#
# 1. create a partition with label secrets-<context> (secrets-balmora)
# 2. format it with cryptsetup luksFormat /dev/disk/by-partlabel/secrets-balmora
# 3. add additional keys with cryptsetup luksAddKey <dev> [key-file]
# 4. make a link to secrets, ln -s ~/bin/secrets ~/bin/secrets-balmora
# 5. clone the repo to the new location, add /mnt/secrets-balmora as remote, main branch: balmora


me=$(basename $0)
path=$(dirname $0)
partlabel=secrets-${me/*-/}

as_me="umask=022,uid=`id -u`,gid=`id -g`"

if [[ $1 =~ ^(i|install) ]]; then
	install -v $0 ~/bin/secrets
elif [[ $1 =~ ^(ls) ]]; then
	mount | grep secrets
elif [[ $1 =~ ^(umount|close|hide) ]]; then
	while ls /dev/mapper/secrets-$me; do
		set +e
		mount | awk "/secrets-$me/ { print \$3 }" | xargs -t sudo umount
		sudo cryptsetup -v close /dev/mapper/secrets-$me
		set -e
	done
elif [[ $me == secrets ]]; then
   echo '# ' make a link...
   echo '# ' cp $path/secrets /usr/local/bin/secrets
   echo '# ' ln -s secrets /usr/local/bin/secrets-caldera
   echo
   grep -E '\$1 =([=~])*.*the[n]' $0 | sed -Ee 's/.*\^//; s/]].*//; s/^\(//; s/\)\s*$//; s/\|/ |  /g'
   exit 1
elif [[ $me =~ secrets-.* ]]; then
	partlabel=secrets-${me/*-/}

	#if [[ -b /dev/disk/by-partlabel/$partlabel ]]; then
	#	echo using /dev/disk/by-partlabel/$partlabel
	#else
	#	sudo cryptsetup open /dev/disk/by-partlabel/$partlabel $partlabel || true 
	#fi
		# is open?
		sudo cryptsetup open /dev/disk/by-partlabel/$partlabel $partlabel || true 
	if [[ ! -b $(realpath /dev/mapper/$partlabel) ]]; then
		echo failed to open $partlabel
		exit 2
	fi
	type=$(blkid /dev/mapper/$partlabel -o value -s TYPE)
	if [[ -z $type ]];then
		echo luks volume is not formatted.
		echo  mkfs.ext2 -L secrets-balmora /dev/mapper/secrets-balmora -b 1024
	fi
	if [[ $type =~ ^ext[0-9] ]]; then
		sudo mkdir -p mkdir /mnt/$partlabel
		set +e
		sudo mount -v /dev/mapper/$partlabel /home/jaroslav/.secrets
		sudo mount -v /dev/mapper/$partlabel /mnt/$partlabel
		set -e
		chmod 700 /home/jaroslav/.secrets
		chmod 700 /mnt/$partlabel
	fi

	if [[ $type =~ ^(ex)*fat ]]; then
		sudo mkdir -p mkdir /mnt/$partlabel
		set +e
		sudo mount -v -o $as_me /dev/mapper/$partlabel /mnt/$partlabel
		sudo mount -v -o $as_me /dev/mapper/$partlabel /home/jaroslav/.secrets
		set -e
	fi
else
   echo hide ' ?'
   partlabel=secrets-${me/*-/}
fi
