#!/bin/bash
set -e


me=$(basename $0)
path=$(dirname $0)

as_me="umask=022,uid=`id -u`,gid=`id -g`"

if [[ $1 =~ ^(i|install) ]]; then
	install -v $0 ~/bin/secrets
elif [[ $1 =~ ^(ls) ]]; then
	mount | grep secrets
elif [[ $1 =~ ^(umount|close|hide) ]]; then
	set +e
	sudo umount -v /dev/mapper/secrets-*
	sudo cryptsetup -v close /dev/mapper/secrets-*
	set -e
elif [[ $me == secrets ]]; then
   echo '# ' make a link...
   echo '# ' cp $path/secrets /usr/local/bin/secrets
   echo '# ' ln -s secrets /usr/local/bin/secrets-caldera
   echo
   grep -E '\$1 =([=~])*.*the[n]' $0 | sed -Ee 's/.*\^//; s/]].*//; s/^\(//; s/\)\s*$//; s/\|/ |  /g'
   exit 1
elif [[ $me =~ secrets-.* ]]; then
	partlabel=secrets-${me/*-/}

	sudo cryptsetup open /dev/disk/by-partlabel/$partlabel $partlabel || true 

	if [[ ! -b $(realpath /dev/mapper/$partlabel) ]]; then
		echo failed to open $partlabel
		exit 2
	fi
	type=$(blkid /dev/mapper/$partlabel -o value -s TYPE)
	if [[ $type =~ ^ext[0-9] ]]; then
		sudo mkdir -p mkdir /mnt/$partlabel
		set +e
		sudo mount -v /dev/mapper/$partlabel /home/jaroslav/.secrets
		sudo mount -v /dev/mapper/$partlabel /mnt/$partlabel
		set -e
	fi

	if [[ $type =~ ^(ex)*fat ]]; then
		sudo mkdir -p mkdir /mnt/$partlabel
		set +e
		sudo mount -v -o $as_me /dev/mapper/$partlabel /mnt/$partlabel
		sudo mount -v -o $as_me /dev/mapper/$partlabel /home/jaroslav/.secrets
		set -e
	fi
else
   echo hide ' ?'
   partlabel=secrets-${me/*-/}
fi
