#!/bin/bash

if [[ $USER != root ]]; then
	exec sudo $0
fi

sensors 'nvme-*' | awk '/^nvme-/ {  printf "%s: ", $1 } /Composite/ { print $2 } '


_smartctl() { sudo  | awk '/[Tt]emp/ { print $NF }'; }

for i in `find /dev -name 'sd?'`; do
	echo $i: $(
		smartctl $i -a | awk '/Model:/ {printf "%s: ", $0 } /[Tt]emp/ { print $NF"°C" }'
		)
done | sed 's/Device.Model:\ \+//'
