#!/bin/bash

#sensors nvme-*

for i in `sensors 'nvme-*' | grep ^nvme-`; do
		sensors $i  | awk 'NR == 1 { sensor=$0 } /Composite/ { temp=$2 } END { print sensor, temp } '
done


_smartctl() { sudo smartctl $1 -a | awk '/[Tt]emp/ { print $NF }'; }

for i in `find /dev -name 'sd?'`; do
	echo $i: $(_smartctl $i)°C
done
