#!/usr/bin/env bash
set -e
#set -o pipefail

if [[ $# -eq 0 ]]; then
    echo $(basename "$0") 1 - find a file at random in current dir
    echo $(basename "$0") c - count files with '"bad"' shebangs
    echo $(basename "$0") ls - list files with '"bad"' shebangs
    echo $(basename "$0") [file] - change that file
    exit
fi

if [[ $1 == rm ]]; then
    rm -fv *.orig-shebang
    exit
fi

function search() {
    rg -L '^#!/bin/bash' -g '!*.orig-shebang' "$@"
}
if [[ $1 == 1 ]] || [[ $1 == one ]]; then
    set -x
    search -l | sort -R | 1q | xargs -tr shebang-env
    exit
fi

if [[ $1 == count ]] || [[ $1 == c ]]; then
    set -x
    search -l -m1  | wc -l
    exit
fi

if [[ $1 == list ]] || [[ $1 == ls ]] || [[ $1 == l ]]; then
    set -x
    search -l
    exit
fi

f=$(realpath "${1:-/usr/local/bin/foobarz.sh}")

sed -i .orig-shebang \
    -e '1s@#!/bin/bash@#!/usr/bin/env bash@w /tmp/shebung.log' \
    -e '1s@#!/bin/sh@#!/usr/bin/env sh@w /tmp/shebung.log' \
    -e '1s@#!/bin/sed -f@#!/usr/bin/env -S sed -f@w /tmp/shebung.log' \
    -e '1s@#!/bin/env sh@#!/usr/bin/env sh@w /tmp/shebung.log' \
    "$f"

trap "echo $f changed; exit 0;" ERR # diff exists with 1 if there are diffs

lines=$( diff -u  $f{.orig-shebang,} 2>&1 ) || :

if [[ -n $lines ]]; then
    echo "$lines" |& grep -e '^[-+]#'
    echo $f changed
fi
