#!/bin/bash -l
keys=(
		$(find ~/.ssh/keys/*.{rsa,dsa,ed25519,pem,priv} 2>/dev/null )
)
if [[ $1 =~ (list|find) ]]; then
	echo ${keys[*]}
	exit 0
fi

A_WEEK=604800
SSH_ADD_LIFE=$A_WEEK

out=$(
	# how to capture only stderr into a var?
	smux "secrets-$(hostname)" "ssh-add ${keys[*]}" #2>&1
)

## if echo $out | grep -q failed; then
## 	echo FAIL >&2
## 	sleep 0.1
## 	exit 1
## fi

echo have $(ssh-add -l | wc -l) keys

{ systemctl --user is-enabled -q vpn \
&& systemctl --user restart vpn & } &

sleep 0.5
bash ~/.Profile/bash/agent-ssh.sh
