#!/bin/bash
pat=SteamLibrary/
pat=steamapps/
locate -r $pat | grep ".*$pat" -o | sort -u | while read p;
do
	grep name "$p/"*.acf \
		| sed 's/"name"//; s/:/@/; s/\t\+//g' \
		| column -ts@ | sort -t'"' -k2;
done
