#!/bin/bash
#set -x

function types() {
	if [[ $# -gt 1 ]]; then
		return
	fi
	local t=$(type $1 2>&1)
	if [[ "$t" =~ 'is.a.function' ]]; then
		echo -e "$t"  | sed 1d
	fi
	if [[ "$t" =~ 'is.aliased.to' ]]; then
		local alias_target=$(
			echo -e "$t"  | grep  -oP "(?<=\`).*(?=')"
		)
		1>&2 echo $1 is aliased to \`$alias_target"'"
		types $alias_target	
	fi

	if [[ "$t" =~ \w+\sis\s\.*/ ]]; then
		ls -l $1
	fi

	if [[ $t =~ [a-z].is ]]; then
		if [[ -L $1 ]] || [[ -L `which "$1"` ]]; then
			type $1
			echo $i iz `realpath "$i"`
		else
			type $1 | awk '{$1=$2=""; print }'
		fi
	fi

	#todo: types mount
	if [[ "$t" =~ "is.\.*/" ]]; then
		type $1
	fi
}

if [[ $# -gt 0 ]];then
	for i; do types $i; done
fi

## todo: report bug to bash

# this rhould return same when run in the shell;
#
#     $ type i  |& grep  -P "(?<=\`).*(?=')" -o 
#     lssort
#
#
#	if echo -e "$t" | grep -q 'is.aliased.to'; then
#		q="'"
#		echo -e "$t"  | grep  -P "(?<=\`).*(?='$)"
#	fi
#
# and not:

#       $ types i 
#       lssort'

