#!/bin/bash

for a in $@;
do
	case $a in
		--list|-list|-l|ls)
			fc-list | awk -F: '{ print $2 }' | tr ',' '\n' | sed -E 's/^\s+//' | sort -u
			exit
			;;
		--help|-help|-h)
			echo "usage: `basename $0` size family style"
			exit
			;;
	esac
done


font=${2:-monospace}
size=${1:-20}
style=${3:-Regular}
if fc-list  | grep -q 'Droid Sans Mono';
then
	font=${2:-Droid Sans Mono}
	size=${1:-13}
elif fc-list  | grep -q 'xos4 Terminus'; then
	font=${2:-"xos4 Terminus"}
	size=${1:-13}
elif fc-list  | grep -q 'Terminus';
then
	font=${2:-Terminus}
	size=${1:-20}
fi

# todo: change italic and bold too
# todo merge with function ufs
printf '\33]50;%s\007' "xft:${font}:pixelsize=${size}:style=${style}"

