#!/bin/bash


declare -a argv=( "$@" )

while getopts ':n' name; do
    case "$name" in
        n)
			no_newline=true
			unset argv[$((OPTIND-2))]
            ;;
        *)
			#argv+=("$name")
			echo pos: 
			echo O: $OPTIND
			echo @: $@
			echo \#: $#
			if [ $# -eq 0 ]; then break; fi
			shift
            ;;
    esac
done

set -- ${argv[@]}

  if [ $# -eq 0 ]; then left_wrap="'";  right_wrap="',";
elif [ $# -eq 1 ]; then left_wrap="$1"; right_wrap="$1";
elif [ $# -eq 2 ]; then left_wrap="$1"; right_wrap="$2"; fi

rs=""

if [ -t 0 ]; then
	echo "pipe elements to me?
seq 1 3 | $(basename $0)
seq 1 3 | $(basename $0) \"
seq 1 3 | $(basename $0) \\b \\>
	" >&2
	>&2 paste \
		<(seq 1 3 | $0; echo) \
		<(seq 1 3 | $0 '"'; echo) \
		<(seq 1 3 | $0 '<' ' />' ; echo)


	exit 1
fi

filter() { cat; }
if [[ $no_newline = true ]]; then
	# filter() { sed -e 's/\n//'; }
	filter() { tr -d '\n' | sed \$s/,$// ; echo; }
fi


cat | sed -e "

	s${rs}^${rs}$left_wrap${rs}
	s${rs}\$${rs}$right_wrap${rs}

" | filter

