#!/usr/bin/env bash
# print out the nth (starting from 1) display in the X11 notation:
#
# - :0.0, :0.1  OR
# - :0.0, :1.0, :2.0
#

n=${0##*-}

if [[ -n $1 ]]; then
	n=$1
fi

declare -a screens=($(
for d in {0..5}; do
	for s in {0..5}; do
		DISPLAY=:$d.$s xrandr &>/dev/null && echo :$d.$s
	done
done
))

if [[ $n -ge 1 ]] && [[ -n ${screens[$((n-1))]} ]]; then
	echo ${screens[$((n-1))]}
	exit 0
fi

exit $((n + 50))
