#!/bin/bash

mk_links() {
		c='eur usd nok rub gbp'
		for i in $c;
		do
			for j in $c;
			do
				if [[ $i != $j ]]; then
					ln -snf ~/bin/xe ~/.local/bin/$i-$j;
				fi
			done
		done
}

#is_num() { echo $1 | grep -Eq '^[\.0-9]{1,}$'; }
is_num() { [[ $1 =~ ^[\.0-9]{1,}$ ]] && return 0 || return 1; }

from_to=$(basename $0)
if [[ ${#from_to} -eq 7 ]]; then
	FROM=${from_to:0:3}
	TO=${from_to:4:7}
	if [ -z "$1" ]; then
		while read i; do
			if is_num $i; then
				xe usd nok $i;
				exit
			else
				exit 1
			fi
		done
	fi;
	if [ -n "$1" ]; then
		#xe usd nok $1;
		AMOUNT=$1
	fi;
else
	if [[ $# -lt 3 ]]; then
		echo $0 FROM TO AMMOUNT
		exit 1
	fi

	num=
	for i in "$@"; do
		if is_num $i; then
			num=$num$i
		elif [[ -z $FROM ]]; then
			FROM=$i
		else
			TO=$i
		fi
	done
	AMOUNT=$num
fi


# {{{
get_free_currency_api() {
	:
	headers=$(mktemp)
	#json=$(curl -D $headers -k "https://free.currencyconverterapi.com/api/v6/convert?q=${FROM}_$TO&compact=y")
	#if grep $headers -q -e ^HTTP.*200; then
	#	rate=$(echo $json | grep -o '[[:digit:]\.]\+')
	#	product=$( echo "scale=6;$AMOUNT*$rate" | bc)
	#	printf "%.2f\n" $product
	#	echo `date --iso-8601` "$AMOUNT $FROM x $rate $TO = $product" >> ~/.xe-results
	#else
	#	echo $json | html2text
	#	echo HISTORY:
	#	grep -e "$FROM.*x.*$TO" ~/.xe-results
	#fi
	rm $headers
}
# }}}

get_conversion_wolfram() {
	local response=$(
		wolfram-alpha $AMOUNT $FROM in $TO \
			| jq -r '.queryresult.pods[] | select(.primary==true) | .subpods[].plaintext'
	)
	if [[ -n $response ]]; then
			#value=$(echo $response | grep -Eo '[[:digit:]]{1,}\.[[:digit:]]{2}' )
			value=$(echo $response | tr ' ' \\n  | grep -E '[0-9\.]+' -m1 -o)
			rate=$(echo "scale=6; $value / $AMOUNT" | bc)
			printf "%.2f\n" $value
			echo `date --iso-8601` "$AMOUNT $FROM x $rate $TO = $value" >> ~/Data/currency-conversion-results
			echo "$AMOUNT $FROM x $rate $TO = $value" >&2
			echo $response >&2
	fi
}

response=$(get_conversion_wolfram)

if [[ -n $response ]]; then
	echo $response
else
	echo HISTORY:
	grep -e "$FROM.*x.*$TO" ~/Data/currency-conversion-results
fi

function currencies() {
# {{{
cat <<MOO
Albania, Leke           ALL
Afghanistan, Afghanis   AFN
Argentina, Pesos        ARS
Aruba, Guilders         AWG
Australia, Dollars      AUD
Azerbaijan, New Manats  AZN
Bahamas, Dollars        BSD
Barbados, Dollars       BBD
Belarus, Rubles         BYR
Belgium, Euro           EUR
Belize, Dollars         BZD
Bermuda, Dollars        BMD
Bolivia, Bolivianos     BOB
Bosnia and Herzegovina, BAM
Botswana, Pulas         BWP
Bulgaria, Leva          BGN
Brazil, Reais           BRL
United Kingdom Pounds   GBP
Brunei Darussalam, Dlrs BND
Cambodia, Riels         KHR
Canada, Dollars         CAD
Cayman Islands, Dollars KYD
Chile, Pesos            CLP
China, Yuan Renminbi    CNY
Colombia, Pesos         COP
Costa Rica, Colon       CRC
Croatia, Kuna           HRK
Cuba, Pesos             CUP
Cyprus, Euro            EUR
Czech Republic, Koruny  CZK
Denmark, Kroner         DKK
Dominican Rep., Pesos   DOP
East Caribbean, Dollars XCD
Egypt, Pounds           EGP
El Salvador, Colones    SVC
Euro                    EUR
Falkland Islands,Pounds FKP
Fiji, Dollars           FJD
France, Euro            EUR
Ghana, Cedis            GHC
Gibraltar, Pounds       GIP
Greece, Euro            EUR
Guatemala, Quetzales    GTQ
Guernsey, Pounds        GGP
Guyana, Dollars         GYD
Netherlands, Euro       EUR
Honduras, Lempiras      HNL
Hong Kong, Dollars      HKD
Hungary, Forint         HUF
Iceland, Kronur         ISK
India, Rupees           INR
Indonesia, Rupiahs      IDR
Iran, Rials             IRR
Ireland, Euro           EUR
Isle of Man, Pounds     IMP
Israel, New Shekels     ILS
Italy, Euro             EUR
Jamaica, Dollars        JMD
Japan, Yen              JPY
Jersey, Pounds          JEP
Kazakhstan, Tenge       KZT
Korea (North), Won      KPW
Korea (South), Won      KRW
Kyrgyzstan, Soms        KGS
Laos, Kips              LAK
Latvia, Lati            LVL
Lebanon, Pounds         LBP
Liberia, Dollars        LRD
Liechtenstein, Francs   CHF
Lithuania, Litai        LTL
Luxembourg, Euro        EUR
Macedonia, Denars       MKD
Malaysia, Ringgits      MYR
Malta, Euro             EUR
Mauritius, Rupees       MUR
Mexico, Pesos           MXN
Mongolia, Tugriks       MNT
Mozambique, Meticais    MZN
Namibia, Dollars        NAD
Nepal, Rupees           NPR
Netherlands Antilles,   ANG
Netherlands, Euro       EUR
New Zealand, Dollars    NZD
Nicaragua, Cordobas     NIO
Nigeria, Nairas         NGN
North Korea, Won        KPW
Norway, Krone           NOK
Oman, Rials             OMR
Pakistan, Rupees        PKR
Panama, Balboa          PAB
Paraguay, Guarani       PYG
Peru, Nuevos Soles      PEN
Philippines, Pesos      PHP
Poland, Zlotych         PLN
Qatar, Rials            QAR
Romania, New Lei        RON
Russia, Rubles          RUB
Saint Helena, Pounds    SHP
Saudi Arabia, Riyals    SAR
Serbia, Dinars          RSD
Seychelles, Rupees      SCR
Singapore, Dollars      SGD
Slovenia, Euro          EUR
Solomon Islands, Dlrs   SBD
Somalia, Shillings      SOS
South Africa, Rand      ZAR
South Korea, Won        KRW
Spain, Euro             EUR
Sri Lanka, Rupees       LKR
Sweden, Kronor          SEK
Switzerland, Francs     CHF
Suriname, Dollars       SRD
Syria, Pounds           SYP
Taiwan, New Dollars     TWD
Thailand, Baht          THB
Trinidad & Tobago, Dlrs TTD
Turkey, Lira            TRY
Turkey, Liras           TRL
Tuvalu, Dollars         TVD
Ukraine, Hryvnia        UAH
United Kingdom, Pounds  GBP
US of America, Dollars  USD
Uruguay, Pesos          UYU
Uzbekistan, Sums        UZS
Vatican City, Euro      EUR
Venezuela, Boliv. Fu.   VEF
Vietnam, Dong           VND
Yemen, Rials            YER
Zimbabwe, Zimbabwe Dlrs ZWD
MOO
# }}}
}

# vim: ft=sh foldmethod=marker
