#!/usr/bin/env bash
set -eu
if [ -t 0 ]; then
	echo "$0 wants input on stdin" >&2

else
    declare -a opt=()

    # set -x
	for i in "$@"; do
        : $i
        if [[ $i =~ ^-(A|B|C)[0-9]+ ]]; then
            opt+=( "$i" )
        else
            opt+=( -e "$i" )
        fi
	done

	exec grep -iaE ${opt[@]}
fi
