#!/bin/bash
# print columns given as arguments
#
# awc 3 4 - print columns 3 and 4
# or...
#
#     $ seq 1 10 | paste - - - - - | awc 1,5
#     1 5
#     6 10
set -eu
argv=
fields=
for i in "$@"; do
	if [[ $1 =~ ^[0-9,]+$ ]]; then
		fields="$fields $1"
	else
		argv="$argv $1"
	fi
	shift
done
fields=${fields//,/ }
awk $argv -v argnum="${fields:-1 2}" '
BEGIN{ split(argnum,cols," ") }
{
    for (i in cols) {
		if ($(cols[i]) != "") {
			printf "%s%s", $(cols[i]), OFS }
		}
	printf "%s", ORS
}
'
