#!/usr/bin/awk -f
BEGIN {
for (i = 1; i < ARGC; i++) { if (ARGV[i] ~ /report=[0-9]+/) { split(ARGV[i], parts, "="); report = parts[2];} }
}
{ if (report && NR % report == 0) { for (i in _) { print _[i], i } } } # report every nth line
{ _[$0]++ } END { for (i in _) { print _[i], i } }

