#!/bin/bash
# print columns given as arguments
#
# awc 3 4 - print columns 3 and 4
# or...
#
#     $ seq 1 10 | paste - - - - - | awc 1,5
#     1 5
#     6 10
set -eu
argv=
fields=
for i in "$@"; do
	if [[ $1 =~ ^-*[0-9,]+$ ]]; then
		fields="$fields $1"
	else
		argv="$argv $1"
	fi
	shift
done
fields=${fields//,/ }

exec awk $argv -v argnum="${fields:-1 2}" '
BEGIN{ split(argnum,cols," "); len=length(cols); }
{
  for (i in cols) {
    field=cols[i]
    if (field < 0 ) {
      field=NF+field+1
    }
    if ($(field) != "") {
      if (NF == cols[i] || len == 1 || i == len) {
         printf "%s", $(field)
      } else {
         printf "%s%s", $(field), OFS
      }
    }
  }
  printf "%s", ORS
}
'
