#!/bin/sh
#df  -B1g -T  -t{btrfs,fuseblk,ext4}  | sort -u -k 1,1 | sort -b -k 2,2 -k 7,7

df-chart "$@"
echo

block=1g unit=gigs
[ "$1" = m ] && { block=1m unit=megs; }
[ "$1" = t ] && { block=1t unit=ters; }

{
	echo fs type $unit used left use% mounted;
	df -B$block -T  -x{fuse.sshfs,overlay,devtmpfs,tmpfs} \
		| grep -v \
			-e tmpfs \
			-e /snap/ \
			-e devtmpfs\
			-e Filesystem \
		| sort -b -k 2,2 -k 1,1 -k 7,7
} \
| column -t \
| sed 's/^/   /'





