#!/bin/bash
function strip_1() { awk ' BEGIN{ RS="\0"} { $1="" ; gsub(/^\s/,"", $0); print }'; }
function strip_1n() { awk '{ $1="" ; gsub(/^\s/,"", $0); print }'; }
function n2z() { tr \\n \\0; }
find=/usr/bin/find
if [[ $0 == *latest0 ]]; then
	$find ${1:-./} -not -path '*/.git/*' -type f -printf "%T@ %p\0" | sort -nz | n2z | strip_1 | n2z
else
	$find ${1:-./} -not -path '*/.git/*' -type f -printf "%T@ %p\n" | sort -n | strip_1n
fi

#find /path/to/search -type d \( -path '*/.git' -o -path '*/.svn' -o -path '*/.hg' -o -path '*/.bzr' -o -path '*/CVS' \) -prune -o -print
