#!/bin/sh
reformat='
  [.[]| with_entries( .key |= ascii_downcase ) ]
        |    (.[0] |keys_unsorted | @tsv)
           , (.[]  |map(.)         |@tsv)
'
tab='	'

exec sh -c "jq -r '$reformat' | column -ts '$tab'"
