#!/usr/bin/env bash


if echo a b | column -t -N A,B &>/dev/null; then
	function table { column -s@ -t -N mem,vsz,rss,comm; }
else
	function table { column -s@ -t; }
fi


function bm() {
	ps -e -o %mem,vsz,rss,comm --no-headers |
		sort -b  -k3,3n -k4,20
}

function s_ {
	sed -Ee 's/^\s+//; s/\s+/@/; s/\s+/@/; s/\s+/@/ '
}

bm | s_ | awk -F@ '$3 { print $1 "@" $2 "@" $3 "@" $4}' | table


echo -e "\n%mem, virtual, rss, comm\n"
echo -e "\ntop-30\n"


bm | s_ | awk -F@ '
{
	_[$4]+=$3;
	pp[$4]++
}

END {
for (i in _) {
	print int(_[i]/1024) , i "(" pp[i] ")", int(_[i]/pp[i]/1024)
}
}' | sort -k 1,1nr | head -n 30




