#!/usr/bin/env bash


declare -a argv=( "$@" )

while getopts ':nr' name; do
    case "$name" in
		r)
			as_regex_or_expression=true
			no_newline=true
			unset argv[$((OPTIND-2))]
			;;
        n)
			no_newline=true
			unset argv[$((OPTIND-2))]
            ;;
        *)
			#argv+=("$name")
			echo pos: 
			echo O: $OPTIND
			echo @: $@
			echo \#: $#
			if [ $# -eq 0 ]; then break; fi
			shift
            ;;
    esac
done

set -- ${argv[@]}

  if [ $# -eq 0 ]; then left_wrap="'";  right_wrap="',";
elif [ $# -eq 1 ]; then left_wrap="$1"; right_wrap="$1";
elif [ $# -eq 2 ]; then left_wrap="$1"; right_wrap="$2"; fi

  if [ $# -eq 0 ] && [[ $as_regex_or_expression == true ]]; then left_wrap='|'; right_wrap=''
elif [ $# -eq 1 ] && [[ $as_regex_or_expression == true ]]; then left_wrap="$1"; right_wrap='';
fi

rs=""

if [ -t 0 ]; then # stdin file descriptor is terminal? show help
	echo "pipe elements to me?
seq 1 3 | $(basename $0)
seq 1 3 | $(basename $0) \"
seq 1 3 | $(basename $0) \\b \\>
seq 1 3 | $(basename $0) -r
	" >&2
	>&2 paste \
		<(seq 1 3 | $0           ; echo) \
		<(seq 1 3 | $0 '"'       ; echo) \
		<(seq 1 3 | $0 '<' ' />' ; echo) \
		<(seq 1 3 | $0 -r        ; echo)
	exit 1
fi

filter() { cat; }
if [[ $no_newline = true ]]; then
	filter() { tr -d '\n' | sed \$s/,$// ; echo; }
fi

if [[ $as_regex_or_expression = true ]]; then
	elems=$(cat | tr '\n' "${left_wrap:-|}" | sed "s/$left_wrap$//")
	echo "egrep '($elems)'"
	exit 0
fi


cat | sed -e "

	s${rs}^${rs}$left_wrap${rs}
	s${rs}\$${rs}$right_wrap${rs}

" | filter

